---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssa-test-redis-data
  labels:
    username: lew2547
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 3Gi
