---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssa-test-redis
  labels:
    app: mssa-test-redis
    username: lew2547
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssa-test-redis
      username: lew2547
      env: test
  template:
    metadata:
      labels:
        username: lew2547
        env: test
        app: mssa-test-redis
    spec:
      containers:
        - name: redis-app
          image: redis:6
          command:
          volumeMounts:
          - name: mssa-test-redis-data-1
            mountPath: "/data"
      volumes:
      - name: mssa-test-redis-data-1
        persistentVolumeClaim:
          claimName: mssa-test-redis-data-1
